AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-get-commits

  Sample SAM Template for mangum-test

Resources:
  DepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: sam-app-dependencies
        Description: Dependencies for sam app
        ContentUri: dependencies
        CompatibleRuntimes:
          - python3.8   
        LicenseInfo: 'MIT'
        RetentionPolicy: Retain

  GithubGetCommitsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: github-get-commits
      CodeUri: app
      Handler: handlers.get_commits
      Timeout: 10
      Policies:
        - AWSLambdaFullAccess
      Layers:
        - !Ref DepLayer
      Runtime: python3.8 
      Events:
        UpdateCommitsEvent:
          Type: Schedule
          Properties:
            Schedule: cron(00 12 ? * MON-FRI *)
